version: "3"
services:
  chrome-node4:
    image: selenium/standalone-chrome:4.1.4-20220427
    container_name: selenium-chrome-node4
    restart: unless-stopped
    ports:
      - "4444:4444"
    shm_size: 8gb
    environment:
      - JAVA_OPTS=-Xmx10g  -XX:-ClassUnloading -XX:-ClassUnloadingWithConcurrentMark  -Dselenium.LOGGER.level=WARNING
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - SCREEN_DPI=74
      - START_XVFB=false
      - SE_NODE_MAX_SESSIONS=96
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=200
    tmpfs:
      - /tmp
  chrome-node:
    image: selenium/standalone-chrome:3.141.59-20210929
    container_name: selenium-chrome-node3
    restart: unless-stopped
    shm_size: 2gb
    ports:
      - "6444:4444"
    environment:
      - JAVA_OPTS=-Xmx10g  -XX:-ClassUnloading -XX:-ClassUnloadingWithConcurrentMark  -Dselenium.LOGGER.level=WARNING
      - SCREEN_WIDTH=1366
      - SCREEN_HEIGHT=768
      - SCREEN_DEPTH=24
      - SCREEN_DPI=74
      - START_XVFB=false
      - SE_NODE_MAX_SESSIONS=96
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=200